### ISSUE TITLE
Customize landing page (Indico instance)

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/dynamics-website#2]
https://talk.getindico.io/t/changing-texts-in-templates/2450

**Comment by stevenweaver** [comment]
Dear Art, 

There were two issues here. 

1) I had to copy the edits of the root_category template to `/opt/indico/.venv/lib/python3.9/site-packages/indico/modules/categories/templates/display/root_category.html`. This is suboptimal, and I believe we could potentially use the customization feature to override templates instead of doing this. 

2) According to the documentation previously linked. 

> Static files may be added in <CUSTOMIZATION_DIR>/files.

I needed to make the following edits to the indico config file. 

```
CUSTOMIZATION_DIR = '/opt/indico/custom'
LOGO_URL = 'static/custom/files/dnelogo.png'
```



Best,
Steven

**Comment by ArtPoon** [comment]
Thanks @stevenweaver !  That URL mapping scheme is so convoluted...
Regarding the root_category template, I agree - I'm pretty sure we're supposed to add files under the `/opt/indico/custom` branch that override the templates.

**Comment by ArtPoon** [comment]
I think the image link is still broken for pages below the web root:
<img width="306" alt="Screen Shot 2022-09-27 at 11 12 50 AM" src="https://user-images.githubusercontent.com/1109328/192565543-25a373ca-d839-4b11-bbbc-4fe3916f7f80.png">

I think `LOGO_URL` is supposed to be an absolute path:
```
LOGO_URL = '/static/custom/files/dnelogo.png'
```
Testing now.

**Comment by ArtPoon** [comment]
Yes that fixed it.
Trying alternate logos now.
Will work on writing template for custom text too.

**Comment by ArtPoon** [comment]
Trying to figure out how to customize text via templates now.  Per these [instructions](https://docs.getindico.io/en/latest/config/settings/#customization), we're to inspect the debug log for tips on where to place the custom template file:
```
(indico) [indico@octamonkey log]$ grep root indico.log | tail -n1
2022-09-27 11:30:19,023  DEBUG    696908d7fc004abd  2       indico.customization      Customizable: core/categories/display/root_category.html (original: /opt/indico/.venv/lib/python3.9/site-packages/indico/modules/categories/templates/display/root_category.html, reference: ~categories/display/root_category.html)
```

**Comment by ArtPoon** [comment]
The "original" path is the file that Steven directly modified.  
As an experiment, I created folders under `/opt/indico/custom/templates`:
* `core/categories/display`
* `core/events`

Next, I tried following [this example](https://indico.cern.ch/event/614422/contributions/2703408/attachments/1543373/2421298/Indico_customization.pdf) to modify the front page header to add a custom title:
```html
{% extends '~header.html' %}

{% block logo %}
    {{ super() }}
    <h1 class="logo-text">Dynamics and Evolution of Human Viruses</h1>
{% endblock %}
```
but this caused a time zone error.

**Comment by ArtPoon** [comment]
Note this is using the Django template language:
https://docs.djangoproject.com/en/4.1/ref/templates/language/

**Comment by ArtPoon** [comment]
Another useful thread:
https://talk.getindico.io/t/how-can-i-add-more-user-titles-and-change-welcome-message/746

**Comment by ArtPoon** [comment]
Success!
